apiVersion: v1
kind: Service
metadata:
  name: ai-risk-scoring-service
  namespace: {{ .Values.namespaceOverride }}
  labels:
    app: ai-risk-scoring
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ai-risk-scoring

