apiVersion: v1
kind: Pod
metadata:
  name: ldapsearch-test
  namespace: horizon-relevance-dev
spec:
  containers:
  - name: ldapsearch
    image: ubuntu:22.04
    command: ["/bin/bash", "-c"]
    args:
      - apt update &&
        apt install -y ldap-utils &&
        sleep 3600
    tty: true
  restartPolicy: Never
