apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan-{{ .Values.scan.id | default (randAlphaNum 5 | lower) }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: trivy-cli-scan
    horizonrelevance.com/scan-id: {{ .Values.scan.id | quote }}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: trivy-cli
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--image"
        - "{{ .Values.scan.imageName }}"
        - "--application"
        - "{{ .Values.scan.application }}"
        - "--repo-url"
        - "{{ .Values.scan.repoUrl }}"
        - "--jenkins-url"
        - "{{ .Values.scan.jenkinsUrl }}"
        - "--jenkins-job"
        - "{{ .Values.scan.jenkinsJob }}"
        - "--build-number"
        - "{{ .Values.scan.buildNumber }}"
        - "--requested-by"
        - "{{ .Values.scan.requestedBy }}"
        - "--fail-on-severity"
        - "{{ .Values.scan.failOnSeverity }}"
        - "--scanners"
        - "{{ .Values.scan.scanners }}"
        {{- if .Values.scan.uploadResults }}
        - "--upload"
        {{- end }}
      restartPolicy: Never
