namespaceOverride: horizon-relevance-dev
replicaCount: 1

image:
  repository: ankur1825/horizon-opa
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
