apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sonarqube.sonarPropertiesSecretName }}
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
stringData:
  sonar.properties: |
    sonar.web.context={{ .Values.sonarqube.webContext }}
    sonar.forceAuthentication=true
    sonar.authenticator.downcase=true

    {{- if .Values.jdbc.enabled }}
    sonar.jdbc.url={{ required "jdbc.url is required when jdbc.enabled=true" .Values.jdbc.url }}
    sonar.jdbc.username={{ .Values.jdbc.username }}
    sonar.jdbc.password={{ .Values.jdbc.password }}
    {{- end }}

    {{- if .Values.ldap.enabled }}
    sonar.security.realm=LDAP
    ldap.url={{ required "ldap.url is required when ldap.enabled=true" .Values.ldap.url }}
    ldap.bindDn={{ required "ldap.bindDn is required when ldap.enabled=true" .Values.ldap.bindDn }}
    {{- $ldapBindPassword := .Values.ldap.bindPassword -}}
    {{- if and (not $ldapBindPassword) .Values.ldap.existingSecret }}
    {{- $secret := lookup "v1" "Secret" .Values.namespaceOverride .Values.ldap.existingSecret -}}
    {{- if and $secret (hasKey $secret.data .Values.ldap.existingSecretKey) -}}
    {{- $ldapBindPassword = (index $secret.data .Values.ldap.existingSecretKey | b64dec) -}}
    {{- end -}}
    {{- end }}
    ldap.bindPassword={{ required "ldap.bindPassword or ldap.existingSecret is required when ldap.enabled=true" $ldapBindPassword }}
    ldap.user.baseDn={{ required "ldap.userBaseDn is required when ldap.enabled=true" .Values.ldap.userBaseDn }}
    ldap.user.request={{ .Values.ldap.userRequest }}
    ldap.user.realNameAttribute={{ .Values.ldap.realNameAttribute }}
    ldap.user.emailAttribute={{ .Values.ldap.emailAttribute }}
    ldap.group.baseDn={{ .Values.ldap.groupBaseDn }}
    ldap.group.request={{ .Values.ldap.groupRequest }}
    ldap.group.idAttribute={{ .Values.ldap.groupIdAttribute }}
    ldap.group.admins={{ .Values.sonarqube.adminGroup }}
    {{- end }}
