{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarqube.fullname" . }}-data
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarqube.fullname" . }}-extensions
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.extensionsSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarqube.fullname" . }}-logs
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logsSize }}
{{- end }}
