apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-server
  namespace: horizon-relevance-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      initContainers:
      - name: fetch-bundle
        image: alpine:3.18
        command: ["/bin/sh", "-c"]
        args:
          - apk add curl tar && curl -sSL https://raw.githubusercontent.com/ankur1825/jenkins-shared-library/main/horizon-relevance-bundle.tar.gz -o /bundles/horizon-relevance-bundle.tar.gz
        volumeMounts:
        - name: opa-bundle
          mountPath: /bundles

      containers:
      - name: opa
        image: o