# opa-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-server
  namespace: horizon-relevance-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        args:
          - "run"
          - "--server"
          - "--addr=0.0.0.0:8181"
          - "/bundles/horizon-relevance-bundle.tar.gz"
        volumeMounts:
        - name: opa-bundle
          mountPath: /bundles
          readOnly: true
      volumes:
      - name: opa-bundle
        configMap:
          name: opa-bundle-config
          items:
            - key: horizon-relevance-bundle.tar.gz
              path: horizon-relevance-bundle.tar.gz  

---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: horizon-relevance-dev
spec:
  ports:
  - port: 8181
    targetPort: 8181
  selector:
    app: opa
